format:
  line_width: 120
  tab_size: 4
  use_tabchars: false
  max_subgroups_hwrap: 2
  max_pargs_hwrap: 2
  dangle_parens: false
  separate_ctrl_name_with_space: true
  separate_fn_name_with_space: false
  enable_sort: true
parse:
  additional_commands_json: []
