repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: local
    hooks:
      - id: cmake-format
        name: cmake-format
        entry: cmake-format
        language: system
        types: [file]
        files: (CMakeLists\.txt|.*\.cmake)$
        args: ["--config-files", ".cmake-format.yaml"]

      - id: uncrustify-fix
        name: uncrustify-fix
        language: python
        entry: python
        args: [scripts/uncrustify_fix.py]
        files: \.(c|cc|cpp|cxx|h|hpp)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies: [prettier]
        files: \.(md|markdown|mdx|json|jsonc|ya?ml|toml)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: [pytest]
