extends: default

rules:
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: consistent
    check-multi-line-strings: false
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy: disable
  trailing-spaces: enable
  new-line-at-end-of-file: enable
  comments-indentation: enable
  key-duplicates: enable
